/**
 * cindy-subagent —— 写进 pi `PI_CODING_AGENT_DIR/extensions/` 的扩展源码(字符串常量)。
 *
 * 为什么是 Cindy 自己的实现,而不是装社区包:
 *  - pi 上游刻意不内置子代理,社区(`pi-subagents` 等)一律以「扩展 + 子 pi 进程」补齐。
 *    但整包引入等于把第三方代码塞进 `pi-harness.md` §4.2 划定的自包含注入边界,并跟着上游
 *    版本跑。这里参考社区与上游示例的设计,只重做我们需要的部分,代码归 Cindy 所有。
 *  - 沿用 §3 设计原则:直接用 pi 自身能力(`--mode json` 子进程、`--tools` 白名单、
 *    `--append-system-prompt`),不再套一层外部框架、不做二次转义。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;只依赖 pi 的
 * ExtensionAPI 与 node 内建。约束(与 cindy-bridge 同):模板里**不得出现模板字符串**,
 * 否则 `${...}` 会被外层 String.raw 插值 —— 一律用字符串拼接。
 *
 * 安全形态(重要,别当冗余删掉):
 *  - 子进程**继承 `PI_CODING_AGENT_DIR`**,因此同样加载 cindy-bridge → 权限门(`tool_call`
 *    拦截 + 凭证路径硬拦)对子代理照样生效。不传 `--no-extensions` 正是为了保住这条。
 *  - 第一期只给**只读**工具白名单(read/grep/find/ls)。这不只是保守:ask 档下非只读工具
 *    要走 `ctx.ui.confirm`,而 headless 子进程没有 UI 承接、bridge 的 catch 分支按 deny
 *    收口(fail-closed)。只读工具在门里直接放行,因此只读子代理开箱可用;写权限子代理需
 *    要先把子进程的确认请求转发到 Cindy 审批 UI,属独立一期。
 *  - `CINDY_PI_SUBAGENT_DEPTH` 防递归:达到上限后本扩展不注册工具,子代理无法再派子代理。
 *  - `--no-session`:子代理不写会话文件,不污染 Cindy 的会话 JSONL。
 *  - **父死子亡**:子进程是 Cindy 的孙进程,`PiRpcProcess.close()` 的 SIGTERM/SIGKILL 只
 *    打到 pi 父进程,孙进程会被 init 收养后继续请求模型烧额度(review)。两条机制兜:
 *    子进程侧的父存活看门狗(见 `CINDY_SUBAGENT_PARENT_WATCHDOG_SOURCE`)+ 父进程侧的
 *    `process.on('exit')` 同步清扫。刻意**不注册信号处理器**,原因见看门狗那段注释。
 *
 * 进度回传走 pi 工具原生的 `onUpdate` 流(→ `tool_execution_update`),由
 * `subagent-progress.ts` 翻成统一 `agent_task_update` → 与 Claude / Codex 共用
 * `AgentTaskCard`。不另开侧信道。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件。
 */

/** 工具名 —— 与 `@cindy/maker-shared` 的 `PI_SUBAGENT_TOOL_NAME` 必须一致(卡片判据靠它)。 */
export const CINDY_SUBAGENT_TOOL_NAME = 'subagent';

export const CINDY_SUBAGENT_EXTENSION_FILENAME = 'cindy-subagent.ts';

/** Cindy 注入给子进程的 env 名:pi 二进制路径、递归深度、子代理模型。 */
export const CINDY_SUBAGENT_ENV = {
  binary: 'CINDY_PI_SUBAGENT_BINARY',
  depth: 'CINDY_PI_SUBAGENT_DEPTH',
  /**
   * 子代理运行期快照文件({model?, provider?})。刻意不用 env 传 model:env 在 spawn 时
   * 定型,会话中途 setModel 后子代理会继续用旧模型;provider 不一起传还会让同名模型落到
   * 错误 endpoint。扩展每次派子代理现读本文件(与权限档同机制)。
   */
  runtimeFile: 'CINDY_PI_SUBAGENT_RUNTIME_FILE',
} as const;

/**
 * 父进程 pid —— 由**父扩展**在 spawn 子代理时注入(不是 host 注入,所以不在
 * `CINDY_SUBAGENT_ENV` 里)。子进程里的看门狗靠它判断父进程是否还活着。
 */
export const CINDY_SUBAGENT_PARENT_PID_ENV = 'CINDY_PI_SUBAGENT_PARENT_PID';

/** 看门狗轮询间隔:也是父进程死亡后子代理最长残留时间。 */
export const CINDY_SUBAGENT_PARENT_WATCHDOG_INTERVAL_MS = 2000;

/**
 * 父存活看门狗 —— 追加在扩展源码末尾(函数声明会提升,所以放最后不影响调用)。
 *
 * 为什么必须由**子进程自己**盯着父进程,而不是父进程负责回收:
 *  - Cindy 的 `PiRpcProcess.close()` 是 SIGTERM → 3s → SIGKILL,两者都只打到 pi 父进程;
 *    孙进程(子代理)不在同一进程组被信号覆盖,会被 init 收养后继续请求模型、烧额度。
 *  - 父进程侧能挂的钩子覆盖不全:`process.on('exit')` 在 SIGTERM 默认终止路径上**不触发**,
 *    SIGKILL 下更不可能有任何代码执行。所以父侧清扫只能当快路径,兜不住主要死法。
 *  - 刻意**不在扩展里注册 `SIGTERM`/`SIGINT` 处理器**:Node/Bun 里一旦添加信号监听,该信号
 *    的默认终止行为就被抑制 —— 如果 pi 自身没有别的处理器,pi 收到 SIGTERM 后不会退出,
 *    每次关会话都得等满 Cindy 的 3s 宽限再被 SIGKILL,把"优雅关闭"变成"必然强杀"。
 *
 * 存活判据用 `process.kill(pid, 0)` —— 只做存在性检查,不真的发信号:
 *  - `EPERM`(进程在、无权发信号)按**活着**处理;其余任何异常都按**已死**处理。方向是刻意
 *    选的:误判成死 = 子代理中途被杀(用户看到一次失败的子代理),误判成活 = 孤儿进程无上限
 *    地烧额度 —— 父进程一死,那个 10min 兜底超时的定时器也跟着消失了,没有第二道闸。
 *  - pid 复用会让判活偏保守(误认为父进程还在),此时只能等子代理自己跑完;这是已知残留风险,
 *    换来的是绝不误杀正在干活的子代理。
 *
 * 平台覆盖:macOS 上已用真 pi 进程实测(父进程 SIGKILL 后子进程 ~1s 自行退出)。Windows 走
 * libuv 的 `OpenProcess` 存在性检查,语义相同但未实测 —— CI 的 Windows 分片会跑本机制的执行级
 * 测试,若那里表现不同,以测试结果为准。
 */
export const CINDY_SUBAGENT_PARENT_WATCHDOG_SOURCE = String.raw`
const PARENT_PID_ENV = 'CINDY_PI_SUBAGENT_PARENT_PID';
const PARENT_WATCHDOG_INTERVAL_MS = 2000;

function installParentWatchdog() {
  const raw = process.env[PARENT_PID_ENV];
  const parentPid = typeof raw === 'string' ? Number.parseInt(raw, 10) : Number.NaN;
  if (!Number.isFinite(parentPid) || parentPid <= 0) return;
  const timer = setInterval(function () {
    let alive = true;
    try {
      process.kill(parentPid, 0);
    } catch (err) {
      // EPERM = 进程在、只是没权限发信号 → 活着。其余(ESRCH 及任何意外错型)按死处理。
      alive = !!err && err.code === 'EPERM';
    }
    if (!alive) {
      clearInterval(timer);
      process.exit(0);
    }
  }, PARENT_WATCHDOG_INTERVAL_MS);
  // unref:看门狗自己不留住事件循环,子代理干完活该退就退。
  if (timer && typeof timer.unref === 'function') timer.unref();
}
`;

const CINDY_SUBAGENT_EXTENSION_BODY = String.raw`/**
 * cindy-subagent (generated by Cindy — do not edit; overwritten on session start)
 */
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';

const TOOL_NAME = 'subagent';
const MARKER = '__cindySubagent';
const BINARY_ENV = 'CINDY_PI_SUBAGENT_BINARY';
const DEPTH_ENV = 'CINDY_PI_SUBAGENT_DEPTH';
const RUNTIME_FILE_ENV = 'CINDY_PI_SUBAGENT_RUNTIME_FILE';
// cindy-bridge 用它决定要不要连 MCP server;子代理不需要,spawn 时剥掉(见 runTask)。
const MCP_BRIDGE_ENV = 'CINDY_PI_MCP_BRIDGE';
// PARENT_PID_ENV 与 PARENT_WATCHDOG_INTERVAL_MS 由末尾追加的看门狗段声明(那段要能独立
// 跑起来受测)。**别在这里重复声明** —— 同名 const 会让拼接后的模块直接 SyntaxError,
// 整个扩展加载失败。有测试守这条。

// 子代理不得再派子代理:深度到顶就不注册工具(与 codex agents.max_depth 同语义)。
const MAX_DEPTH = 1;
const MAX_TASKS = 8;
const MAX_CONCURRENCY = 4;
// 回给父模型的单任务输出上限:子代理的价值是"只回结论",别把全文灌回主线程。
const MAX_OUTPUT_CHARS = 16000;
// **调用级**总预算。只限单项没用:8 个任务各 16k 拼起来仍是 ~128k 字符注进父请求,
// 一次委派就能把父上下文吃掉大半(review)。成功与全失败两条返回路径都要过这道闸。
const MAX_TOTAL_OUTPUT_CHARS = 32000;
// 兜底超时:卡死的子代理不能把父 turn 永久挂住。
const TASK_TIMEOUT_MS = 10 * 60 * 1000;

// 只读画像。tools 同时是 --tools 白名单:非只读工具在 ask 档会被 bridge fail-closed
// 拒掉(headless 子进程没有确认 UI),所以第一期只给只读能力。
const PROFILES = {
  scout: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a scout subagent. Investigate the codebase and answer the question you were given. '
      + 'Read only what you need. Report conclusions with file:line anchors — never paste long file contents. '
      + 'Be concise: the parent agent only needs your findings, not your process.',
  },
  reviewer: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a code review subagent. Review what you were asked to review and report concrete, '
      + 'actionable defects with file:line anchors, most severe first. State the failure scenario for each. '
      + 'Do not restate what the code does. If you find nothing real, say so plainly.',
  },
  planner: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a planning subagent. Read the relevant code, then produce a concrete implementation plan: '
      + 'which files change, in what order, and what could break. Cite file:line for every claim about current '
      + 'behavior. Do not write code.',
  },
};

function profileNames() {
  return Object.keys(PROFILES).join(' | ');
}

/**
 * 现读子代理运行期快照(model + provider)。每次派子代理都读 —— 会话中途 setModel 后
 * 立即生效。
 *
 * 读不到返回空对象,调用方**必须据此失败关闭**:退回 pi 默认解析会把 BYOM / 本地
 * provider 的请求发到错误 endpoint,那比"本次没有子代理"糟糕得多(review)。
 */
function readRuntimeSnapshot() {
  const file = process.env[RUNTIME_FILE_ENV];
  if (typeof file !== 'string' || file.length === 0) return {};
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    if (!parsed || typeof parsed !== 'object') return {};
    const model = typeof parsed.model === 'string' && parsed.model.trim().length > 0
      ? parsed.model.trim()
      : undefined;
    const provider = typeof parsed.provider === 'string' && parsed.provider.trim().length > 0
      ? parsed.provider.trim()
      : undefined;
    // pending = host 已写入这份路由但 pi 侧还没确认(set_model RPC 在飞)。这段窗口里派发是
    // 不安全的:用它就是用未确认的 provider,RPC 若被拒,子进程已经起来了、撤不回。
    return { model: model, provider: provider, pending: parsed.pending === true };
  } catch (err) {
    console.error('[cindy-subagent] runtime snapshot unreadable: ' + String(err));
    return {};
  }
}

function readDepth() {
  const raw = process.env[DEPTH_ENV];
  const parsed = typeof raw === 'string' ? Number.parseInt(raw, 10) : 0;
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

/**
 * 在途子代理进程。父进程正常退出(stdin EOF / 显式 process.exit)时同步强杀,免得
 * 孙进程被 init 收养后继续烧额度。SIGTERM / SIGKILL 覆盖不到这里 —— 那两条由子进程
 * 侧的 installParentWatchdog() 兜。
 */
const liveChildren = new Set();

function reapLiveChildren() {
  for (const child of liveChildren) {
    try {
      // exit 处理器里只能做同步动作:SIGKILL 一次到位,不给宽限期(没有下一轮事件循环)。
      child.kill('SIGKILL');
    } catch (err) {
      /* already gone */
    }
  }
  liveChildren.clear();
}

function clampText(text, max) {
  if (typeof text !== 'string') return '';
  const trimmed = text.trim();
  if (trimmed.length <= max) return trimmed;
  return trimmed.slice(0, max - 1) + '…';
}

/**
 * 调用级输出预算。单项 16k 之上还需要一道总闸:8 个任务拼起来 ~128k 字符会把父上下文
 * 吃掉大半(review)。
 *
 * 先均分,再把短任务省下的额度让给超额任务 —— 常见形态是一个任务话多、其余很短,直接
 * 均分会把长任务砍得没必要地狠。截断只切尾部,'## <agent> (failed)' 头部与失败诊断的
 * 开头一定保留,不会因为超预算就丢掉"哪个任务失败了"这个信息。
 */
function fitSectionsToBudget(sections) {
  let total = 0;
  for (const section of sections) total += section.length;
  if (total <= MAX_TOTAL_OUTPUT_CHARS || sections.length === 0) return sections;

  let share = Math.floor(MAX_TOTAL_OUTPUT_CHARS / sections.length);
  let surplus = 0;
  let overCount = 0;
  for (const section of sections) {
    if (section.length <= share) surplus += share - section.length;
    else overCount += 1;
  }
  if (overCount > 0) share += Math.floor(surplus / overCount);

  return sections.map(function (section) {
    return section.length <= share ? section : clampText(section, share);
  });
}

/** 归一化入参成任务数组;抛出的错误直接回给模型(它能据此改调用)。 */
function normalizeTasks(params) {
  const input = params && typeof params === 'object' ? params : {};
  const raw = Array.isArray(input.tasks) && input.tasks.length > 0
    ? input.tasks
    : [{ agent: input.agent, task: input.task }];
  if (raw.length > MAX_TASKS) {
    throw new Error('subagent: at most ' + MAX_TASKS + ' tasks per call (got ' + raw.length + ')');
  }
  return raw.map(function (entry, index) {
    const item = entry && typeof entry === 'object' ? entry : {};
    const agent = typeof item.agent === 'string' ? item.agent.trim() : '';
    const task = typeof item.task === 'string' ? item.task.trim() : '';
    if (!Object.prototype.hasOwnProperty.call(PROFILES, agent)) {
      throw new Error('subagent: unknown agent "' + agent + '" (available: ' + profileNames() + ')');
    }
    if (!task) {
      throw new Error('subagent: task ' + (index + 1) + ' is missing a task description');
    }
    return { agent: agent, task: task };
  });
}

/** 逐行喂 JSONL:pi 的 --mode json 每行一个事件,chunk 边界可能切断一行。 */
function createLineReader(onLine) {
  let buffer = '';
  return function (chunk) {
    buffer += chunk;
    for (;;) {
      const newline = buffer.indexOf('\n');
      if (newline < 0) break;
      const line = buffer.slice(0, newline).trim();
      buffer = buffer.slice(newline + 1);
      if (line.length > 0) onLine(line);
    }
  };
}

function assistantTextOf(message) {
  if (!message || typeof message !== 'object') return '';
  const content = Array.isArray(message.content) ? message.content : [];
  const parts = [];
  for (const block of content) {
    if (block && typeof block === 'object' && block.type === 'text' && typeof block.text === 'string') {
      parts.push(block.text);
    }
  }
  return parts.join('');
}

function emptyUsage() {
  return { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0 };
}

/**
 * 累加子代理的一条 message_end.usage。
 *
 * 分量必须**逐项**留着,不能只汇总成一个 tokens:父进程要把这些委派用量并进本 turn 的
 * 记账(input/output/cacheRead/cacheWrite 各自成列,外加 cost.total),register.ts 持久化
 * 的 session 用量才包含委派请求。只给一个总数的话父侧无从拆分(review)。
 */
function addUsage(totals, usage) {
  if (!usage || typeof usage !== 'object') return;
  const keys = ['input', 'output', 'cacheRead', 'cacheWrite'];
  for (const key of keys) {
    const value = usage[key];
    if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
      totals[key] += value;
      totals.tokens += value;
    }
  }
  const cost = usage.cost && typeof usage.cost.total === 'number' && Number.isFinite(usage.cost.total)
    ? usage.cost.total
    : 0;
  if (cost > 0) totals.cost += cost;
}

function mergeUsage(target, source) {
  if (!source) return;
  const keys = ['input', 'output', 'cacheRead', 'cacheWrite', 'cost'];
  for (const key of keys) {
    const value = source[key];
    if (typeof value === 'number' && Number.isFinite(value) && value > 0) target[key] += value;
  }
}

/** 跑一个子代理,返回 { text, isError, toolUses, tokens }。 */
function runTask(binary, task, runtime, signal, onProgress) {
  return new Promise(function (resolve) {
    // 已中止就**根本不 spawn**。批次被取消时 worker 车道里可能还排着好几个任务,原来它们照样
    // 先 spawn 出子进程、再走到下面那个 aborted 早返回 —— 而那个 return 发生在注册
    // stdout / error / close 之前:子进程永远留在 liveChildren 里(父进程退出时才被清),
    // 而一次 spawn 失败会变成**无人监听的 'error' 事件**,在 Node 里直接抛出、能把父 pi
    // 进程带走。反复中断的批次因此既攒僵尸 handle 又有整进程崩掉的风险(review)。
    if (signal && signal.aborted === true) {
      resolve({ text: 'subagent aborted by user.', isError: true, toolUses: 0, tokens: 0, usage: emptyUsage() });
      return;
    }
    const profile = PROFILES[task.agent];
    const args = [
      '--mode', 'json',
      '--no-session',
      '--tools', profile.tools,
      '--append-system-prompt', profile.prompt,
    ];
    // provider 与 model 成对传:pi-harness §3 要求 BYOM / 本地模型直连对应原生 provider,
    // 只给 model 会让网关与 BYOM 同名模型落到默认 provider。
    if (runtime.provider) args.push('--provider', runtime.provider);
    if (runtime.model) args.push('--model', runtime.model);
    args.push(task.task);

    const childEnv = Object.assign({}, process.env);
    // 深度 +1:子代理进程里本扩展不再注册工具。
    childEnv[DEPTH_ENV] = String(readDepth() + 1);
    // 父 pid:子进程里的看门狗据此在父进程消失后自杀(SIGTERM/SIGKILL 打不到孙进程)。
    childEnv[PARENT_PID_ENV] = String(process.pid);
    // MCP 桥必须剥掉。子进程继承 PI_CODING_AGENT_DIR 会加载 cindy-bridge(权限门要靠这个,
    // 见文件头),而 bridge 一见到 CINDY_PI_MCP_BRIDGE 就会**逐个 connect 所有 MCP server**
    // 并持有有状态 transport。子代理的 --tools 白名单里根本没有 MCP 工具,所以这些连接纯属
    // 浪费:每个子代理一整套连接、每次派发一轮连接风暴(并发 4、单次最多 8),而且子代理不会
    // 显式 close,只能等进程退出(review)。这也是来源隔离不变量:子代理不能继承 root
    // bridge；未来若开放 MCP，Host 必须为子进程签发 descendant provenance。
    // 剥这一个变量即可 —— 权限门与网关路由不受影响。
    delete childEnv[MCP_BRIDGE_ENV];

    let child;
    try {
      child = spawn(binary, args, { cwd: process.cwd(), env: childEnv, stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (err) {
      resolve({ text: 'subagent failed to start: ' + String(err), isError: true, toolUses: 0, tokens: 0, usage: emptyUsage() });
      return;
    }
    liveChildren.add(child);

    const totals = emptyUsage();
    totals.tokens = 0;
    let toolUses = 0;
    let finalText = '';
    let stderr = '';
    let settled = false;
    let timer = null;
    // 强杀定时器:存下来才能在子进程真的退出后清掉(见 kill())。
    let killTimer = null;
    /**
     * 中止 / 超时的原因。置上它之后**不立刻 finish**,而是等 'close' 再收口 —— 这样 SIGTERM
     * 到 SIGKILL 之间那 2 秒宽限里子进程仍会吐出的 message_end 用量能被正常归集。
     *
     * 原来是"置守卫 + 立刻 finish":守卫连 JSON 解析一起跳过,已经真实产生的 token/cost 就
     * 丢了(review)。而单纯"解析但不上报"也救不回来 —— promise 已经 resolve,调用方紧接着就
     * 读走了那份快照,之后再改 totals 没人再看。所以正解是**推迟收口到进程真的关闭**。
     */
    let terminationReason = null;
    /** 收口兜底:'close' 万一不来(进程卡死在 SIGKILL 之外),不能把父 turn 永久挂住。 */
    let settleFallbackTimer = null;
    const armSettleFallback = function (result) {
      if (settleFallbackTimer) return;
      settleFallbackTimer = setTimeout(function () {
        settleFallbackTimer = null;
        finish(result);
      }, 5000);
      if (settleFallbackTimer && typeof settleFallbackTimer.unref === 'function') settleFallbackTimer.unref();
    };
    // 先声明:finish 在闭包里引用它,let 的 TDZ 不容许"定义在后、可能先被读"。
    let removeAbort = null;

    const finish = function (result) {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      if (typeof removeAbort === 'function') removeAbort();
      resolve(result);
    };

    const kill = function () {
      try {
        child.kill('SIGTERM');
      } catch (err) {
        /* already gone */
      }
      // 宽限后强杀,避免僵尸子进程把 turn 挂住。定时器**存下来**并在 close/error 时清掉:
      // 留着它不仅让进程在退出后仍多挂 2 秒,更重要的是强杀前必须重新确认子进程还没退 ——
      // 否则一旦 pid 被系统回收复用,这一发 SIGKILL 就打到了别人身上(review)。
      // 双重保险:先查 exitCode/signalCode,再走 child.kill(Node 对已退出的 handle 是 no-op)。
      if (killTimer) return;
      killTimer = setTimeout(function () {
        killTimer = null;
        if (child.exitCode !== null || child.signalCode !== null) return;
        try {
          child.kill('SIGKILL');
        } catch (err) {
          /* already gone */
        }
      }, 2000);
      if (killTimer && typeof killTimer.unref === 'function') killTimer.unref();
    };

    const onAbort = function () {
      // 不立刻 finish:先杀,等 'close' 收口,期间继续归集用量(见 terminationReason 注释)。
      terminationReason = 'aborted';
      kill();
      armSettleFallback({ text: 'subagent aborted by user.', isError: true, toolUses: toolUses, tokens: totals.tokens, usage: totals });
    };
    if (signal && typeof signal.addEventListener === 'function') {
      if (signal.aborted) {
        // 残余竞态:上面的 spawn 前检查过后、spawn 完成前信号才置位。此时进程已经存在,而这条
        // 早返回仍在注册 stdout / error / close 之前 —— 必须自己把两件事做掉:从 liveChildren
        // 摘除(否则僵尸 handle 留到父进程退出),以及挂一个吞掉 'error' 的监听(ChildProcess
        // 的 'error' 无人监听会在 Node 里直接抛出,能把父 pi 进程带走)。
        liveChildren.delete(child);
        child.on('error', function () { /* 已中止,spawn 失败无需上报 */ });
        kill();
        finish({ text: 'subagent aborted by user.', isError: true, toolUses: 0, tokens: 0, usage: emptyUsage() });
        return;
      }
      signal.addEventListener('abort', onAbort, { once: true });
      removeAbort = function () {
        try {
          signal.removeEventListener('abort', onAbort);
        } catch (err) {
          /* ignore */
        }
      };
    }

    timer = setTimeout(function () {
      terminationReason = 'timeout';
      kill();
      armSettleFallback({
        text: 'subagent timed out after ' + Math.round(TASK_TIMEOUT_MS / 1000) + 's.',
        isError: true,
        toolUses: toolUses,
        tokens: totals.tokens,
        usage: totals,
      });
    }, TASK_TIMEOUT_MS);
    if (timer && typeof timer.unref === 'function') timer.unref();

    const feed = createLineReader(function (line) {
      // 终态已收口后丢弃迟到输出。注意**只跳过上报、不跳过解析**:kill() 到 SIGKILL 之间
      // 有约 2 秒宽限,子进程仍会吐 message_end,那里面是真实产生的 token/cost。原来在
      // JSON.parse 之前就整条短路,把这段用量丢了(review)。
      // 现在 abort / timeout 都推迟到 'close' 才 finish,所以这段窗口里 settled 仍为 false、
      // 用量照常归集;settled 为 true 只剩"兜底定时器已强行收口"这一种情况,此时上报会把
      // 已发出的 stopped/failed 改回 running,必须挡住。
      if (settled) return;
      let event;
      try {
        event = JSON.parse(line);
      } catch (err) {
        return;
      }
      if (!event || typeof event !== 'object') return;
      if (event.type === 'tool_execution_start') {
        toolUses += 1;
        const toolName = event.toolName || (event.tool && event.tool.name) || '';
        onProgress({
          toolUses: toolUses,
          tokens: totals.tokens,
          usage: totals,
          transcript: { role: 'tool', content: toolName ? 'Using ' + toolName : 'Using a tool', toolName: toolName },
        });
        return;
      }
      if (event.type === 'message_end') {
        const message = event.message;
        if (message && message.role === 'assistant') {
          addUsage(totals, message.usage);
          const text = assistantTextOf(message);
          // 覆盖为最新一条有文本的 assistant 回复 = 子代理的结论。
          if (text.trim().length > 0) finalText = text;
          onProgress({
            toolUses: toolUses,
            tokens: totals.tokens,
            usage: totals,
            transcript: text.trim().length > 0 ? { role: 'subagent', content: text } : undefined,
          });
        }
      }
    });

    child.stdout.setEncoding('utf8');
    child.stdout.on('data', feed);
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', function (chunk) {
      if (stderr.length < 4000) stderr += chunk;
    });
    child.on('error', function (err) {
      liveChildren.delete(child);
      if (killTimer) { clearTimeout(killTimer); killTimer = null; }
      finish({ text: 'subagent process error: ' + String(err), isError: true, toolUses: toolUses, tokens: totals.tokens, usage: totals });
    });
    child.on('close', function (code) {
      // 到 'close' 才摘除,不在 finish() 里摘:超时/中止已 finish 但进程还在 SIGKILL 宽限
      // 期里,这段窗口内父进程退出仍必须把它杀掉。
      liveChildren.delete(child);
      // 进程已退出:强杀定时器必须清掉,别对一个可能被复用的 pid 再发 SIGKILL(review)。
      if (killTimer) { clearTimeout(killTimer); killTimer = null; }
      if (terminationReason !== null) {
        // 中止/超时的收口点:等到进程真的关闭,此刻 totals 已含宽限期内到达的全部用量。
        if (settleFallbackTimer) { clearTimeout(settleFallbackTimer); settleFallbackTimer = null; }
        finish({
          text: terminationReason === 'timeout'
            ? 'subagent timed out after ' + Math.round(TASK_TIMEOUT_MS / 1000) + 's.'
            : 'subagent aborted by user.',
          isError: true,
          toolUses: toolUses,
          tokens: totals.tokens,
          usage: totals,
        });
        return;
      }
      const ok = code === 0;
      const body = finalText.trim().length > 0
        ? clampText(finalText, MAX_OUTPUT_CHARS)
        : (ok ? '(subagent produced no output)' : clampText(stderr, 2000) || ('subagent exited with code ' + String(code)));
      finish({ text: body, isError: !ok, toolUses: toolUses, tokens: totals.tokens, usage: totals });
    });
  });
}

export default async function cindySubagent(pi: any) {
  // depth > 0 = 本进程自己就是子代理:装上父存活看门狗,父进程(pi 会话)一消失就自杀。
  // 必须在下面的深度早返回**之前**装 —— 子代理正是走那条早返回分支的。
  if (readDepth() > 0) installParentWatchdog();
  if (readDepth() >= MAX_DEPTH) return;
  const binary = process.env[BINARY_ENV];
  // 拿不到 pi 二进制路径就不注册:宁可没有这个工具,也不让模型调用一个必然失败的工具。
  if (typeof binary !== 'string' || binary.trim().length === 0) return;
  // host 未能持久化路由快照时会**不传**该 env → 本次会话完全不暴露子代理工具(fail-closed)。
  const runtimeFile = process.env[RUNTIME_FILE_ENV];
  if (typeof runtimeFile !== 'string' || runtimeFile.trim().length === 0) return;

  // 父侧快路径:pi 正常退出(stdin EOF / 显式 exit)时同步清掉在途子代理。信号死法覆盖不到
  // 这里(SIGTERM 的默认终止不跑 'exit' 处理器),那部分由子进程侧看门狗兜。
  process.on('exit', reapLiveChildren);

  pi.registerTool({
    name: TOOL_NAME,
    label: 'Subagent',
    description: 'Delegate a focused, read-only investigation to a subagent running in its own context window. '
      + 'Use it for exploration whose intermediate output does not need to stay in this conversation: reading '
      + 'rule or design docs, surveying large or unfamiliar files, broad code searches, or getting an '
      + 'independent review. The subagent reports conclusions only. Available agents: ' + profileNames() + '. '
      + 'Pass {agent, task} for one, or {tasks:[{agent, task}, ...]} to run up to ' + MAX_TASKS + ' in parallel. '
      + 'Subagents are read-only (no bash, no file edits) and cannot spawn further subagents — do implementation '
      + 'and verification yourself.',
    parameters: {
      type: 'object',
      properties: {
        agent: { type: 'string', description: 'Agent profile: ' + profileNames() },
        task: {
          type: 'string',
          description: 'What to investigate. State exactly what to read and which question to answer.',
        },
        tasks: {
          type: 'array',
          description: 'Run several subagents in parallel (max ' + MAX_TASKS + ').',
          items: {
            type: 'object',
            properties: {
              agent: { type: 'string', description: 'Agent profile: ' + profileNames() },
              task: { type: 'string' },
            },
            required: ['agent', 'task'],
          },
        },
      },
      additionalProperties: false,
    },
    async execute(toolCallId: string, params: unknown, signal: AbortSignal, onUpdate: any) {
      const tasks = normalizeTasks(params);
      const runtime = readRuntimeSnapshot();
      const startedAt = Date.now();
      const label = tasks.map(function (t) { return t.agent; }).join(', ');
      const taskId = String(toolCallId || 'subagent');
      const totals = { toolUses: 0, tokens: 0, usage: emptyUsage() };
      const perTask = tasks.map(function () { return { toolUses: 0, tokens: 0, usage: emptyUsage() }; });
      // 子代理工作过程只存在于**本子进程内**;父进程拿不到它的 stdout,而 --no-session
      // 也不落盘。只能在这里边跑边留存,随终态帧一次交出去(运行中帧不带,避免每次进度
      // 都重传整份内容)。上限与 host 侧收窄一致,防止长会话把事件撑爆。
      const transcript: Array<Record<string, unknown>> = [];
      const noteTranscript = function (role: string, content: string, toolName?: string) {
        if (transcript.length >= 500) return;
        const text = typeof content === 'string' ? content : '';
        if (!text) return;
        const entry: Record<string, unknown> = {
          role: role,
          content: text.length > 65536 ? text.slice(0, 65535) + '…' : text,
          occurredAt: Date.now(),
        };
        if (toolName) entry.toolName = toolName;
        transcript.push(entry);
      };

      const report = function (status: string, summary?: string) {
        if (typeof onUpdate !== 'function') return;
        const details: Record<string, unknown> = {
          taskId: taskId,
          status: status,
          agentName: label,
          task: tasks.length === 1 ? tasks[0].task : tasks.length + ' parallel tasks',
          toolUses: totals.toolUses,
          totalTokens: totals.tokens,
          durationMs: Date.now() - startedAt,
          // 委派用量的**累计**分量。父进程按 taskId 记住上次值、只把增量并进本 turn 的记账
          // (register.ts 持久化的 session token/cost 因此包含子代理请求)。报累计而不是增量:
          // 进度帧是 best-effort 的,丢一帧不该让那部分用量永久消失(review)。
          usage: {
            input: totals.usage.input,
            output: totals.usage.output,
            cacheRead: totals.usage.cacheRead,
            cacheWrite: totals.usage.cacheWrite,
            cost: totals.usage.cost,
          },
        };
        details[MARKER] = 1;
        if (summary) details.summary = summary;
        if (runtime.model) details.model = runtime.model;
        if (status !== 'running' && transcript.length > 0) details.transcript = transcript;
        try {
          onUpdate({ content: [{ type: 'text', text: status === 'running' ? 'Running subagent…' : status }], details: details });
        } catch (err) {
          /* progress is best-effort */
        }
      };

      const recompute = function () {
        let toolUses = 0;
        let tokens = 0;
        const usage = emptyUsage();
        for (const entry of perTask) {
          toolUses += entry.toolUses;
          tokens += entry.tokens;
          mergeUsage(usage, entry.usage);
        }
        totals.toolUses = toolUses;
        totals.tokens = tokens;
        totals.usage = usage;
      };

      // 两道**派发前**的失败关闭闸。注意它们排在 report 定义**之后**、report('running')
      // **之前**:卡片状态机在没有任何 agent_task_update 时会按"有工具结果 = completed"兜底,
      // 所以在这里直接 throw 会让卡片瞬间变绿 —— 明明这次委派被拒了(review)。必须先发一帧
      // 终态 failed,再抛错。
      //
      // 使用点失败关闭:快照读不到(host 写失败后删除 / 目录只读 / 磁盘满)时拒绝派发,
      // 而不是不带 --provider/--model 让子进程走 pi 默认解析 —— 后者会把 BYOM / 本地
      // provider 的请求发到错误 endpoint。provider 恒由 host 写入,缺它即视为不可用。
      if (!runtime.provider) {
        report('failed', 'model routing snapshot unavailable');
        throw new Error(
          'subagent is unavailable: Cindy could not read this session\'s model routing snapshot, '
          + 'so a subagent would run against the wrong provider. Tell the user; do the work yourself.',
        );
      }
      // 模型切换的等待窗口(host 已写新路由、pi 侧尚未确认)里一律不派发。放行就意味着子进程
      // 用一个**未经确认**的 provider 起来:切换若被拒,host 能回滚文件,却撤不回已经在跑的子
      // 进程 —— 那才是真正撤不回的父子路由分叉(review)。宁可这一次委派失败。
      if (runtime.pending) {
        report('failed', 'model switch in progress; routing not confirmed');
        throw new Error(
          'subagent is unavailable right now: this session is switching model/provider and the new route '
          + 'is not confirmed yet. Do this step yourself, or retry the delegation after the switch settles.',
        );
      }

      report('running');

      const results: any[] = new Array(tasks.length);
      let next = 0;
      const worker = async function () {
        for (;;) {
          const index = next;
          next += 1;
          if (index >= tasks.length) return;
          results[index] = await runTask(binary, tasks[index], runtime, signal, function (progress: any) {
            perTask[index] = { toolUses: progress.toolUses, tokens: progress.tokens, usage: progress.usage };
            if (progress.transcript) {
              noteTranscript(progress.transcript.role, progress.transcript.content, progress.transcript.toolName);
            }
            recompute();
            report('running');
          });
          perTask[index] = {
            toolUses: results[index].toolUses,
            tokens: results[index].tokens,
            usage: results[index].usage,
          };
          recompute();
          report('running');
        }
      };
      const lanes = Math.min(MAX_CONCURRENCY, tasks.length);
      const running = [];
      for (let i = 0; i < lanes; i += 1) running.push(worker());
      await Promise.all(running);

      const failed = results.filter(function (r) { return r && r.isError; }).length;
      const aborted = signal && signal.aborted === true;
      const sections = results.map(function (result, index) {
        const head = '## ' + tasks[index].agent + (result && result.isError ? ' (failed)' : '');
        return head + '\n' + (result ? result.text : '(no result)');
      });
      const text = fitSectionsToBudget(sections).join('\n\n');
      // 任一子任务失败即整卡 failed:部分成功不足以把批次报成完成(greptile P1)。
      report(aborted ? 'stopped' : failed > 0 ? 'failed' : 'completed',
        failed > 0 ? failed + ' of ' + results.length + ' subagents failed' : undefined);

      if (failed === results.length && results.length > 0) {
        throw new Error(text);
      }
      return {
        content: [{ type: 'text', text: text }],
        details: {
          tasks: tasks.map(function (t, index) {
            return {
              agent: t.agent,
              task: t.task,
              isError: results[index] ? results[index].isError === true : true,
              toolUses: perTask[index].toolUses,
              tokens: perTask[index].tokens,
            };
          }),
        },
      };
    },
  });
}
`;

/**
 * 最终注入的扩展源码 = 主体 + 看门狗段。
 *
 * 看门狗单独成段、拼在最后,是为了让它能在测试里被**原样执行**(真起进程验证"父死子亡"),
 * 而不是只做字符串结构断言。函数声明会提升,所以放在末尾不影响主体调用。
 */
export const CINDY_SUBAGENT_EXTENSION_SOURCE =
  CINDY_SUBAGENT_EXTENSION_BODY + CINDY_SUBAGENT_PARENT_WATCHDOG_SOURCE;

